# Generated by Django 5.2.7 on 2025-10-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('status', models.CharField(choices=[('todo', 'TODO'), ('doing', 'DOING'), ('done', 'DONE')], max_length=10)),
                ('created_at', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
